"""migrate fields

Revision ID: cf887339af4c
Revises: 693b332c9a52
Create Date: 2025-09-22 17:00:03.265606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf887339af4c'
down_revision: Union[str, Sequence[str], None] = '693b332c9a52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mining_state', sa.Column('energy', sa.Integer(), nullable=False))
    op.add_column('mining_state', sa.Column('multiplier', sa.Integer(), nullable=False))
    op.alter_column('mining_state', 'earned',
               existing_type=sa.NUMERIC(precision=18, scale=6),
               type_=sa.Integer(),
               nullable=False)
    op.drop_column('mining_state', 'hashrate')
    op.add_column('users', sa.Column('username', sa.String(length=128), nullable=False))
    op.drop_index(op.f('ix_users_tg_id'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'name')
    op.drop_column('users', 'tg_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tg_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_tg_id'), 'users', ['tg_id'], unique=True)
    op.drop_column('users', 'username')
    op.add_column('mining_state', sa.Column('hashrate', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('mining_state', 'earned',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=18, scale=6),
               nullable=True)
    op.drop_column('mining_state', 'multiplier')
    op.drop_column('mining_state', 'energy')
    # ### end Alembic commands ###
